### ISSUE TITLE
Pandora error when loading add-on - log attached

### ISSUE THREAD

**Issue by njloki30** [rivy/xbmc-script.audio.pandora#27]
On Kodi 17.1 I'm trying to launch the Pandora add on, but it errors. Log shows this - 
18:47:30.645 T:1945620480   ERROR: GetDirectory - Error getting plugin://
18:47:30.645 T:1945620480   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
18:47:44.107 T:1538384816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_MPLAYER'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.xbmc.pandora/default.py", line 246, in <module>
                                                panda = Panda()
                                              File "/home/pi/.kodi/addons/script.xbmc.pandora/default.py", line 97, in __init__
                                                self.player = PandaPlayer( panda = self )
                                              File "/home/pi/.kodi/addons/script.xbmc.pandora/pandaplayer.py", line 7, in __init__
                                                xbmc.Player.__init__( self, xbmc.PLAYER_CORE_MPLAYER )
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_MPLAYER'
                                            -->End of Python script error report<-

Not sure what is missing here. any help appreciated.

**Comment by njloki30** [comment]
Nevemind you can close this. the fix was to update the medii player setttings in pandaplayer.py

import xbmc
from threading import Timer

class PandaPlayer( xbmc.Player ):

	def __init__( self, core=None, panda=None ):
		xbmc.Player.__init__( self, xbmc.Player )
		self.panda = panda
		self.timer = None

	def playSong( self, item ):
		print "PANDORA: Item 0 %s" % item[0]
		print "PANDORA: Item 1 %s" % item[1]
		self.play( item[0], item[1] )

	def play( self, url, item ):
		#xbmc.Player(xbmc.PLAYER_CORE_MPLAYER).play( url, item )
		xbmc.Player().play( url, item )
